export const ORDER_ERROR_CODES = {
  PRODUCT_INVALID: 'ORDER_ERROR_CODES.PRODUCT_INVALID',
  QUANTITY_INVALID: 'ORDER_ERROR_CODES.QUANTITY_INVALID',
  ORDER_DETAILS_INVALID: 'ORDER_ERROR_CODES.ORDER_DETAILS_INVALID',
};
